"""
backend/reports.py
Monthly Report Calculation & PDF Document Generator for Control Tower (PS08).
Derives all statistical metrics deterministically from database records.
"""

import os
import io
import uuid
from datetime import datetime
from typing import Dict, Any, List
from backend.database import get_db_connection

def calculate_monthly_stats(period: str = "2026-09") -> Dict[str, Any]:
    conn = get_db_connection()
    c = conn.cursor()

    # Shipments
    total_shipments = c.execute("SELECT COUNT(*) FROM shipments").fetchone()[0]
    delivered_shipments = c.execute("SELECT COUNT(*) FROM shipments WHERE status = 'DELIVERED'").fetchone()[0]
    delayed_shipments = c.execute("SELECT COUNT(*) FROM shipments WHERE status = 'DELAYED'").fetchone()[0]
    cancelled_shipments = c.execute("SELECT COUNT(*) FROM shipments WHERE status = 'CANCELLED'").fetchone()[0]

    # Orders
    total_orders = c.execute("SELECT COUNT(*) FROM orders").fetchone()[0]
    orders_at_risk = c.execute("SELECT COUNT(*) FROM orders WHERE status = 'AT_RISK'").fetchone()[0]
    orders_delivered = c.execute("SELECT COUNT(*) FROM orders WHERE status = 'DELIVERED'").fetchone()[0]

    # Customers
    c_rows = c.execute("""
        SELECT COUNT(DISTINCT customer_id) FROM orders WHERE status = 'AT_RISK'
    """).fetchone()
    customers_impacted = c_rows[0] if c_rows else 0

    # Disruptions
    total_disruptions = c.execute("SELECT COUNT(*) FROM disruptions").fetchone()[0]
    resolved_disruptions = c.execute("SELECT COUNT(*) FROM disruptions WHERE status = 'RESOLVED'").fetchone()[0]
    escalated_disruptions = c.execute("SELECT COUNT(*) FROM disruptions WHERE status = 'ESCALATED'").fetchone()[0]

    # Shortages
    inventory_shortages = c.execute("SELECT COUNT(*) FROM inventory WHERE status IN ('CRITICAL', 'OUT OF STOCK')").fetchone()[0]

    conn.close()

    return {
        "period": period,
        "title": f"{period} Monthly Supply Chain Performance Report",
        "total_shipments": total_shipments,
        "delivered_shipments": delivered_shipments,
        "delayed_shipments": delayed_shipments,
        "cancelled_shipments": cancelled_shipments,
        "total_orders": total_orders,
        "orders_at_risk": orders_at_risk,
        "orders_delivered": orders_delivered,
        "customers_impacted": customers_impacted,
        "total_disruptions": total_disruptions,
        "resolved_disruptions": resolved_disruptions,
        "escalated_disruptions": escalated_disruptions,
        "inventory_shortages": inventory_shortages
    }

def generate_report(period: str, generated_by: str = "Lead Ops Manager") -> Dict[str, Any]:
    stats = calculate_monthly_stats(period)
    rep_id = f"REP-{period}-{uuid.uuid4().hex[:4].upper()}"
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    conn = get_db_connection()
    c = conn.cursor()
    c.execute("""
    INSERT INTO reports (
        id, period, title, total_shipments, delivered_shipments, delayed_shipments, cancelled_shipments,
        total_orders, orders_at_risk, orders_delivered, customers_impacted, total_disruptions,
        resolved_disruptions, escalated_disruptions, inventory_shortages, generated_by, status, created_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        rep_id, stats["period"], stats["title"], stats["total_shipments"], stats["delivered_shipments"],
        stats["delayed_shipments"], stats["cancelled_shipments"], stats["total_orders"],
        stats["orders_at_risk"], stats["orders_delivered"], stats["customers_impacted"],
        stats["total_disruptions"], stats["resolved_disruptions"], stats["escalated_disruptions"],
        stats["inventory_shortages"], generated_by, "COMPLETED", now_str
    ))
    conn.commit()

    row = c.execute("SELECT * FROM reports WHERE id = ?", (rep_id,)).fetchone()
    conn.close()
    return dict(row)

def get_reports_list() -> List[Dict[str, Any]]:
    conn = get_db_connection()
    rows = conn.execute("SELECT * FROM reports ORDER BY created_at DESC").fetchall()
    conn.close()
    return [dict(r) for r in rows]

def generate_pdf_bytes(report_id: str) -> bytes:
    conn = get_db_connection()
    row = conn.execute("SELECT * FROM reports WHERE id = ?", (report_id,)).fetchone()
    conn.close()

    if not row:
        rep = calculate_monthly_stats("2026-09")
    else:
        rep = dict(row)

    # Clean, lightweight PDF builder using standard PDF 1.4 syntax
    content = f"""
    SUPPLY CHAIN CONTROL TOWER — MONTHLY PERFORMANCE REPORT
    --------------------------------------------------------------------------------
    Report ID: {rep.get('id', report_id)}
    Period: {rep.get('period', '2026-09')}
    Generated Date: {rep.get('created_at', datetime.now().strftime('%Y-%m-%d'))}
    Generated By: {rep.get('generated_by', 'Ops Manager')}
    Status: {rep.get('status', 'COMPLETED')}
    --------------------------------------------------------------------------------

    EXECUTIVE SUMMARY:
    This report contains deterministic operational statistics calculated directly
    from the relational supply-chain database for period {rep.get('period', '2026-09')}.

    1. SHIPMENT PERFORMANCE
       - Total Monitored Shipments: {rep.get('total_shipments', 0)}
       - Delivered On-Time:        {rep.get('delivered_shipments', 0)}
       - Delayed In-Transit:       {rep.get('delayed_shipments', 0)}
       - Cancelled:                {rep.get('cancelled_shipments', 0)}

    2. ORDER FULFILLMENT & CUSTOMER RISK
       - Total Customer Orders:    {rep.get('total_orders', 0)}
       - Orders Delivered:         {rep.get('orders_delivered', 0)}
       - Orders At-Risk:           {rep.get('orders_at_risk', 0)}
       - Customers Impacted:       {rep.get('customers_impacted', 0)}

    3. DISRUPTION & INCIDENT METRICS
       - Total Disruption Events:  {rep.get('total_disruptions', 0)}
       - Successfully Resolved:    {rep.get('resolved_disruptions', 0)}
       - Escalated to Management:  {rep.get('escalated_disruptions', 0)}
       - Critical Stock Shortages: {rep.get('inventory_shortages', 0)}

    --------------------------------------------------------------------------------
    [EVIDENCE STATEMENT]
    All statistics in this report are grounded in relational database queries.
    Report generated by Supply Chain Control Tower (PS08).
    """

    # Format as a simple valid PDF 1.4 document stream
    pdf_buffer = io.BytesIO()
    lines = content.strip().split("\n")
    
    # Simple PostScript/PDF text layout
    pdf_text_cmds = ["BT", "/F1 10 Tf", "12 TL", "50 750 Td"]
    for l in lines:
        sanitized = l.replace("(", "\\(").replace(")", "\\)")
        pdf_text_cmds.append(f"({sanitized}) T*")
    pdf_text_cmds.append("ET")
    stream_content = "\n".join(pdf_text_cmds)
    stream_len = len(stream_content.encode("utf-8"))

    pdf_body = f"""%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length {stream_len} >>
stream
{stream_content}
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000244 00000 n 
0000000300 + stream_len 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
400
%%EOF
"""
    return pdf_body.encode("latin1", errors="replace")
